---
- name: Ruby on Rails Ansible Playbook by RailsOnVPS.com
  hosts: webservers
  remote_user: deploy
  become: yes
  roles:
    - common
    - deploy-user
    - src: https://github.com/ANXS/postgresql
      version: v1.12.0
      name: ANXS.postgresql
    - redis
    - sidekiq
    - nginx
    - certbot
    - ruby
    - rails
