---
- name: Ruby on Rails Ansible Playbook by RailsOnVPS.com
  hosts: webservers
  remote_user: deploy
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - common
    - deploy-user
    - geerlingguy.nodejs
    - role: ANXS.postgresql
      vars:
        postgresql_databases:
        - name: "{{ app_name }}"
        postgresql_users:
          - name: "{{ app_name }}"
            pass: "{{ database_password }}"
    - redis
    - sidekiq
    - nginx
    - certbot
    - ruby
    - rails
