---
- name: Ruby on Rails Ansible Playbook by RailsOnVPS.com
  hosts: webservers
  remote_user: deploy
  become: yes
  roles:
    - common
    - deploy-user
    - ANXS.postgresql
    - redis
    - sidekiq
    - nginx
    - certbot
    - ruby
    - rails
