---
- name: Create certbot directory
  file: path=/opt/certbot state=directory mode=0755 owner=root group=root

- name: Install certbot standalone
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /opt/certbot/certbot-auto

- name: Ensure certbot-auto is executable.
  file:
    path: /opt/certbot/certbot-auto
    mode: 0755

- name: Get initial certificate
  command: "/opt/certbot/certbot-auto certonly --non-interactive --quiet --agree-tos --email {{ email }} --standalone --pre-hook 'service nginx stop' --post-hook 'service nginx start' -d {{ domain }}"
  notify: restart nginx

- name: Add cerbot renewel cronjob
  cron: name="renew letsencrypt certificates" hour="0" minute="0" job="/bin/bash /opt/certbot/certbot-auto renew --non-interactive --quiet --standalone --pre-hook 'service nginx stop' --post-hook 'service nginx start'"
