- name: Set locale to {{locale}}
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}

- name: Set /etc/timezone to {{ timezone }}
  template: src=etc/timezone dest=/etc/timezone
  notify: update tzdata
