---
- name: Gather facts
  setup:

- name: Perform Safe Upgrade
  apt: upgrade=safe update_cache=yes

- import_tasks: hostname.yml
- import_tasks: tools.yml
- import_tasks: yarn.yml
- import_tasks: locale.yml
- import_tasks: security.yml
